Removed unused variable d_width from ssocr.c (spotted by GCC).
This fixes the following compilation error:

cc -Wall -W -Wextra -pedantic -Werror -pedantic-errors  -O6   -c -o ssocr.o ssocr.c
ssocr.c: In function ‘main’:
ssocr.c:963:21: error: variable ‘d_width’ set but not used [-Werror=unused-but-set-variable]
cc1: all warnings being treated as errors
make: *** [ssocr.o] Error 1

The compiler is right, the value of d_width is never used, the variable is
not useful and can be removed.

My regression tests all pass. :-)